# SIMULATES eyetracker by using the mouse
monitor_devices:
    - Experiment:
        name: ease_infant_audiovisual

    - eyetracker.hw.mouse.EyeTracker:
        enable: True

        name: tracker

        save_events: True

        stream_events: True

        event_buffer_length: 1024

        controls:
            move: [LEFT_BUTTON,]
            blink: [LEFT_BUTTON, RIGHT_BUTTON]
            saccade_threshold: 0.5
        monitor_event_types: [ MonocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]

data_store:
    enable: True
    experiment_info:
        title: Infant visual search with audio stimuli and eye tracking
    session_info:
        code: EXPERIMENT_RUN
