# Configurations for iohub (ie configurations for eyetracker-related configurations, in this
# case) are based on the template 'Default Device Settings' @
# https://www.psychopy.org/api/iohub/device/eyetracker_interface/Tobii_Implementation_Notes.html
# and feedback as described in this forum thread
# https://discourse.psychopy.org/t/guidance-on-using-eyetracking-with-iohub-and-yaml-files-post-2021-2-0/24473/
# You should update the configurations here in accordance with the eyetracker you are using.

monitor_devices:
    - Experiment:
        name: infant_audiovisual_eyetracking

    # tobii eye tracker configuration
    - eyetracker.hw.tobii.EyeTracker:
        # Indicates if the device should actually be loaded at experiment runtime.
        enable: True

        # The variable name of the device that will be used to access the ioHub Device class
        # during experiment run-time, via the devices.[name] attribute of the ioHub
        # connection or experiment runtime class.
        name: tracker

        # Should eye tracker events be saved to the ioHub DataStore file when the device
        # is recording data ?
        save_events: True

        # Should eye tracker events be sent to the Experiment process when the device
        # is recording data ?
        stream_events: True

        # How many eye events (including samples) should be saved in the ioHub event buffer before
        # old eye events start being replaced by new events. When the event buffer reaches
        # the maximum event length of the buffer defined here, older events will start to be dropped.
        event_buffer_length: 1024

        # The Tobii implementation of the common eye tracker interface supports the
        # BinocularEyeSampleEvent event type.
        monitor_event_types: [ BinocularEyeSampleEvent,]

        # The model name of the Tobii device that you wish to connect to can be specified here,
        # and only Tobii systems matching that model name will be considered as possible candidates for connection.
        # If you only have one Tobii system connected to the computer, this field can just be left empty.
        model_name:

        # The serial number of the Tobii device that you wish to connect to can be specified here,
        # and only the Tobii system matching that serial number will be connected to, if found.
        # If you only have one Tobii system connected to the computer, this field can just be left empty,
        # in which case the first Tobii device found will be connected to.
        serial_number:

        runtime_settings:
            # The supported sampling rates for Tobii are model dependent.
            sampling_rate: 600

            # Tobii implementation supports BINOCULAR tracking mode only.
            track_eyes: BINOCULAR
            
        # manufacturer_name is used to store the name of the maker of the eye tracking
        # device. This is for informational purposes only.
        manufacturer_name: Tobii Technology

# specify ioHub data storage options
data_store:
    enable: True
    experiment_info:
        title: Infant visual search with audio stimuli and eye tracking
    session_info:
        code: NEW_SUBJECT
